### PR TITLE
update to version 2.9.1

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #4 #5 #7 #10

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/gperftools . Note that due to https://github.com/conda-forge/status/issues/125, all builds fail currently :-(

**Comment by xmnlab** [comment]
thanks @matthiasdiener, LGTM! 
just lets wait for the conda-forge issue to be resolved and we can run the CI again.
also, thanks for pointing to the conda-forge gh issue

**Comment by matthiasdiener** [comment]
@conda-forge-admin restart ci

**Comment by xmnlab** [comment]
@matthiasdiener , thank you so much for improving the recipe!

**Comment by matthiasdiener** [comment]
> @matthiasdiener , thank you so much for improving the recipe!

Thank you @xmnlab! I'll start working on getting the other architectures working with the package.

**Comment by xmnlab** [comment]
> Thank you @xmnlab! I'll start working on getting the other architectures working with the package.

that would be great! thanks!

**Pull request merged**
